// components/LoginForm.vue
<template>
  <div class="w-full max-w-sm">
    <div class="text-center mb-8">
      <h2 class="text-3xl font-bold text-gray-900 mb-2">Welcome Back!</h2>
      <p class="text-gray-500 text-sm">Please login to access your account.</p>
    </div>

    <form @submit.prevent="handleSubmit" class="space-y-6">
      <div>
        <label for="email" class="block text-sm font-medium text-gray-700 mb-1">
          Email Address
        </label>
        <input
          id="email"
          type="email"
          placeholder="you@example.com"
          class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-brand-purple focus:ring-2 focus:ring-brand-purple/20 outline-none transition-all duration-200 bg-gray-50 focus:bg-white"
          required
          :disabled="isLoading"
        />
      </div>

      <div>
        <label for="password" class="block text-sm font-medium text-gray-700 mb-1">
          Password
        </label>
        <input
          id="password"
          type="password"
          placeholder="••••••••"
          class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-brand-purple focus:ring-2 focus:ring-brand-purple/20 outline-none transition-all duration-200 bg-gray-50 focus:bg-white"
          required
          :disabled="isLoading"
          @focus="emit('setShy', true)"
          @blur="emit('setShy', false)"
        />
      </div>

      <div class="flex items-center justify-between text-sm">
        <label class="flex items-center space-x-2 cursor-pointer">
          <input type="checkbox" class="rounded border-gray-300 text-brand-purple focus:ring-brand-purple" />
          <span class="text-gray-600">Remember me</span>
        </label>
        <a href="#" class="text-brand-purple font-medium hover:underline">Forgot Password?</a>
      </div>

      <button
        type="submit"
        :disabled="isLoading"
        :class="`w-full py-3.5 rounded-xl font-bold text-white transition-all duration-200 transform active:scale-95 shadow-lg shadow-brand-purple/30 
          ${isLoading ? 'bg-gray-400 cursor-not-allowed' : 'bg-gray-900 hover:bg-gray-800'}`"
      >
        <div v-if="isLoading" class="flex items-center justify-center space-x-2">
          <svg class="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <span>Logging in...</span>
        </div>
        <span v-else>Log In</span>
      </button>
    </form>

    <div class="relative my-8">
      <div class="absolute inset-0 flex items-center">
        <div class="w-full border-t border-gray-200"></div>
      </div>
      <div class="relative flex justify-center text-sm">
        <span class="px-2 bg-white text-gray-500">Or continue with</span>
      </div>
    </div>

    <button 
      type="button"
      class="w-full flex items-center justify-center space-x-3 bg-white border border-gray-300 text-gray-700 py-3 rounded-xl hover:bg-gray-50 hover:border-gray-400 transition-colors duration-200 font-medium"
    >
      <svg class="h-5 w-5" aria-hidden="true" viewBox="0 0 24 24">
        <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4" />
        <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
        <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05" />
        <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335" />
      </svg>
      <span>Google</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { LoginState } from '../types';

interface Props {
  loginState: LoginState;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  setShy: [value: boolean];
  login: [];
}>();

const isLoading = computed(() => props.loginState === LoginState.LOADING);

const handleSubmit = () => {
  emit('login');
};
</script>

// components/LoginForm.tsx
import React from 'react';
import { LoginState } from '../types';

interface LoginFormProps {
  setIsShy: (shy: boolean) => void;
  onLogin: () => void;
  loginState: LoginState;
}

const LoginForm: React.FC<LoginFormProps> = ({ setIsShy, onLogin, loginState }) => {
  const isLoading = loginState === LoginState.LOADING;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onLogin();
  };

  return (
    <div className="w-full max-w-sm">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-2">Welcome Back!</h2>
        <p className="text-gray-500 text-sm">Please login to access your account.</p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <div>
          <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
            Email Address
          </label>
          <input
            id="email"
            type="email"
            placeholder="you@example.com"
            className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-brand-purple focus:ring-2 focus:ring-brand-purple/20 outline-none transition-all duration-200 bg-gray-50 focus:bg-white"
            required
            disabled={isLoading}
          />
        </div>

        <div>
          <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
            Password
          </label>
          <input
            id="password"
            type="password"
            placeholder="••••••••"
            className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-brand-purple focus:ring-2 focus:ring-brand-purple/20 outline-none transition-all duration-200 bg-gray-50 focus:bg-white"
            required
            disabled={isLoading}
            onFocus={() => setIsShy(true)}
            onBlur={() => setIsShy(false)}
          />
        </div>

        <div className="flex items-center justify-between text-sm">
            <label className="flex items-center space-x-2 cursor-pointer">
                <input type="checkbox" className="rounded border-gray-300 text-brand-purple focus:ring-brand-purple" />
                <span className="text-gray-600">Remember me</span>
            </label>
            <a href="#" className="text-brand-purple font-medium hover:underline">Forgot Password?</a>
        </div>

        <button
          type="submit"
          disabled={isLoading}
          className={`w-full py-3.5 rounded-xl font-bold text-white transition-all duration-200 transform active:scale-95 shadow-lg shadow-brand-purple/30 
            ${isLoading ? 'bg-gray-400 cursor-not-allowed' : 'bg-gray-900 hover:bg-gray-800'}`}
        >
          {isLoading ? (
            <div className="flex items-center justify-center space-x-2">
              <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <span>Logging in...</span>
            </div>
          ) : (
            'Log In'
          )}
        </button>
      </form>

      <div className="relative my-8">
        <div className="absolute inset-0 flex items-center">
          <div className="w-full border-t border-gray-200"></div>
        </div>
        <div className="relative flex justify-center text-sm">
          <span className="px-2 bg-white text-gray-500">Or continue with</span>
        </div>
      </div>

      <button 
        type="button"
        className="w-full flex items-center justify-center space-x-3 bg-white border border-gray-300 text-gray-700 py-3 rounded-xl hover:bg-gray-50 hover:border-gray-400 transition-colors duration-200 font-medium"
      >
        <svg className="h-5 w-5" aria-hidden="true" viewBox="0 0 24 24">
          <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4" />
          <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
          <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05" />
          <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335" />
        </svg>
        <span>Google</span>
      </button>
    </div>
  );
};

export default LoginForm;
